name: go_zero
description: A project to save the world.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/arrows/
     - assets/icons/
     - assets/logo/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        
  # Um Weights herauszufinden: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight